Devel (#1)
* tmux configuration merge

* tmux configuration merge

* dotfiles +x

* gitconfig split

* Add gitconfig back

* Refactor Vim, s/NeoBundle/Pathogen

* Add .gitconfig.loc.example

* More comprehensive (and correct) Brewfile

* OSX workstation setup scripts

* Ensure the latest BASH completions are installed/enabled

* Add table_color_test function

* table_color_test credits

* Tab autocomplete on hidden files please

* Consistency: functions should be well defined

* Tap fonts

* Fix tap and install Anonymous Pro font

* Add ssh-copy-id and watch - comment out experimentals

* Add Google Drive

* Better to copy secrets instead of symlinking

* Verbosity improved

* Operator precendence and verbosity

* Early OSX confs

* Disabling Docker, enabling Spotify

* Source ~/.secrets (copied) + iTerm2 integration

* Add jq

diff --git a/link/.bash.d/60_completion b/link/.bash.d/60_completion
--- a/link/.bash.d/60_completion
+++ b/link/.bash.d/60_completion
@@ -5,6 +5,9 @@ function load_all_completions() {
   command -v brew >/dev/null 2>&1 || { 
     echo >&2 "Homebrew not found. Aborting BASH completion."; return 1; }
 
+  brew list bash-completion2 >/dev/null 2>&1 || {
+    echo >&2 "Homebrew bash-completion2 not found. Aborting BASH completion."; return 1; }
+
   local cpath="$(brew --prefix)/etc/bash_completion.d"
   local disabled="$cpath/git-prompt.sh $cpath/hg-completion.bash"
 
